AutoFeed: true
MineSpawners: true
BannedSpawners:
  - Pig
  - Cow
  - Villager
Crops: true
CustomRecipes:
  Chest: true
DeathBook:
  BannedWorlds:
    - world_nether
  BookOnRespawn: true
  Enabled: false
Language: english
NoTrample: true
Tools:
  AutoArmor:
    Enabled: true
    Priorities:
      Chain: 3
      Diamond: 5
      Netherite: 6
      Gold: 2
      Iron: 4
      Leather: 1
  BetterHoes: false
  InfiniteTorch: true
  SwitchArmor: true
  TotemInInv: true
  Workbench: true
UpdateNotification: true
VillagerAdditions:
  Drops: true
  EmeraldDropChance:
    Drop: 2
    DropChance: 50
    Randomize: true
  Leash: true
